function createfigure(XData1, YData1, XData2, YData2, XData3, YData3, XData4, YData4, XData5, YData5, X1, Y1, X2, YMatrix1, X3, X4, Y2, YData6)
	% CREATEFIGURE(XData1, YData1, XData2, YData2, XData3, YData3, XData4, YData4, XData5, YData5, X1, Y1, X2, YMatrix1, X3, X4, Y2, YData6)
	% 
	%  Inputs: 
	%  XData1: line xdata
	%  YData1: line ydata
	%  XData2: line xdata
	%  YData2: line ydata
	%  XData3: line xdata
	%  YData3: line ydata
	%  XData4: line xdata
	%  YData4: line ydata
	%  XData5: line xdata
	%  YData5: line ydata
	%  X1: vector of x data
	%  Y1: vector of y data
	%  X2: vector of x data
	%  YMatrix1: matrix of y data
	%  X3: vector of x data
	%  X4: vector of x data
	%  Y2: vector of y data
	%  YData6:  line ydata
	% 
	%  Auto-generated by MATLAB on 12-Feb-2020 07:36:53
	%  Updated on 08-11-2022
	figure1 = figure;
	axes1 = axes('Parent', figure1);
	hold(axes1, 'on');

	% Create line
	line(XData1, YData1, 'Parent', axes1);
	line(XData2, YData2, 'Parent', axes1);
	line(XData3, YData3, 'Parent', axes1, 'Color', [0 0 1]);
	line(XData4, YData4, 'Parent', axes1);
	line(XData5, YData5, 'Parent', axes1);
	plot(X1, Y1, 'Marker', '*', 'LineStyle', 'none', 'Color', [1 0 0]);

	% Create multiple lines using matrix input to plot
	plot1 = plot(X2, YMatrix1, 'Marker', '*', 'LineStyle', 'none', 'Color', [1 0 0], ...
				 'Parent', axes1);
	set(plot1(3), 'Marker', '.', 'Color', [0 0 1]);
	plot(X3, YData4, 'Marker', '*', 'LineStyle', 'none', 'Color', [1 0 0]);
	plot(X4, Y2, 'Marker', '*', 'LineStyle', 'none', 'Color', [1 0 0]);
	line(XData2, YData3, 'Parent', axes1, 'LineStyle', '--', 'Color', [0 0 1]);
	line(XData3, YData6, 'Parent', axes1, 'LineStyle', '--', 'Color', [0 0 1]);
	ylabel('Radius (mm)');
	xlabel('Length (mm)');

	% Uncomment the following line to preserve the X-limits of the axes
	% xlim(axes1,[0 80]);

	% Uncomment the following line to preserve the Y-limits of the axes
	% ylim(axes1,[0 20]);

	grid(axes1,'on');
	set(axes1,'DataAspectRatio',[1 1 1],'PlotBoxAspectRatio',[40 10 1]);
	annotation(figure1,'textarrow',[0.151190476190476 0.131547619047619],...
		[0.705075533661741 0.752052545155993],'String',{'A'});
	annotation(figure1,'textarrow',[0.494642857142857 0.514285714285715],...
		[0.71264367816092 0.749410509031198],'String',{'B'});
	annotation(figure1,'textarrow',[0.697619047619048 0.674404761904764],...
		[0.597701149425287 0.57699671592775],'String',{'D'});
	annotation(figure1,'textarrow',[0.554761904761905 0.520238095238096],...
		[0.763546798029557 0.784893267651888],'String',{'C'});
	annotation(figure1,'textarrow',[0.651785714285714 0.668452380952381],...
		[0.51788341543514 0.540229885057471],'String',{'E'});
	annotation(figure1,'textarrow',[0.886904761904762 0.901785714285715],...
		[0.579638752052545 0.548440065681445],'String',{'F'});
end